#ifndef EXPLORATIONSTATE_H_INCLUDED
#define EXPLORATIONSTATE_H_INCLUDED

enum ExplorationState {
	eUNEXPLORED = 0,
	eEXPLORED_BY_PLAYER = 1,
	eEXPLORED_AT_START = 2
};

#endif // EXPLORATIONSTATE_H_INCLUDED
