# Trivial ZIP config:
SET(CPACK_GENERATOR "ZIP")
SET(PACKAGE_NAME ${PROJECT_NAME})
SET(CPACK_INSTALL_CMAKE_PROJECTS "${PROJECT_BINARY_DIR};${PACKAGE_NAME};ALL;/")
SET(CPACK_PACKAGE_FILE_NAME "${PROJECT_NAME}-v${${PROJECT_NAME}_VERSION}-${CMAKE_SYSTEM_NAME}")
INCLUDE(CPack)
