# INSTALL commands

# Required Vars:
# ${TARGETNAME}

SET(INSTALL_INCDIR include)
SET(INSTALL_BINDIR bin)
IF(WIN32)
	SET(INSTALL_LIBDIR ${INSTALL_BINDIR})
	SET(INSTALL_ARCHIVEDIR ${INSTALL_BINDIR})
ELSE()
	SET(INSTALL_LIBDIR ${INSTALL_BINDIR}${LIB_POSTFIX})
	SET(INSTALL_ARCHIVEDIR ${INSTALL_BINDIR}${LIB_POSTFIX})
ENDIF()

INSTALL(
	TARGETS ${TARGETNAME}
	RUNTIME DESTINATION ${INSTALL_BINDIR} COMPONENT mainComponent
	LIBRARY DESTINATION ${INSTALL_LIBDIR} COMPONENT mainComponent
)
