# Utility functions and macros for finders

# Defines ${TARGETNAME}_CONFIG_FILE with path to config file
FUNCTION(FIND_CONFIG_FILE TARGETNAME)
	STRING(TOLOWER ${TARGETNAME} TARGETNAME_LOWER)

	FIND_FILE(${TARGETNAME}_CONFIG_FILE
		NAMES ${TARGETNAME}Config.cmake ${TARGETNAME_LOWER}-config.cmake
		HINTS ${ARGN}
	)
	SET(TMP ${${TARGETNAME}_CONFIG_FILE})
	UNSET(${TARGETNAME}_CONFIG_FILE CACHE)		# Undefine temporary variable
	SET(${TARGETNAME}_CONFIG_FILE ${TMP} PARENT_SCOPE)
ENDFUNCTION()

# Includes config file pointed by ${TARGETNAME}_CONFIG_FILE if found
MACRO(INCLUDE_CONFIG_FILE TARGETNAME)
	IF(${TARGETNAME}_CONFIG_FILE)
		INCLUDE(${${TARGETNAME}_CONFIG_FILE})
	ENDIF()
ENDMACRO()

# Defines ${TARGETNAME}_VERSION_* (MAJOR, MINOR, PATCH) from a string
MACRO(PARSE_VERSION_NUMBER VARNAME TARGETNAME)
	IF(${VARNAME})
		string(REGEX REPLACE "^([0-9]+).*$" "\\1" ${TARGET_NAME}_VERSION_MAJOR "${${VARNAME}}")
		string(REGEX REPLACE "^[0-9]+\\.([0-9]+).*$" "\\1" ${TARGET_NAME}_VERSION_MINOR "${${VARNAME}}")
		string(REGEX REPLACE "^[0-9]+\\.[0-9]+\\.([0-9]+).*$" "\\1" ${TARGET_NAME}_VERSION_PATCH "${${VARNAME}}")
	ENDIF()
	IF(NOT ${TARGET_NAME}_VERSION_MAJOR OR ${TARGET_NAME}_VERSION_MAJOR STREQUAL ${VARNAME})
		SET(${TARGET_NAME}_VERSION_MAJOR "0")
	ENDIF()
	IF(NOT ${TARGET_NAME}_VERSION_MINOR OR ${TARGET_NAME}_VERSION_MINOR STREQUAL ${VARNAME})
		SET(${TARGET_NAME}_VERSION_MINOR "0")
	ENDIF()
	IF(NOT ${TARGET_NAME}_VERSION_PATCH OR ${TARGET_NAME}_VERSION_PATCH STREQUAL ${VARNAME})
		SET(${TARGET_NAME}_VERSION_PATCH "0")
	ENDIF()
ENDMACRO()
