#! /bin/bash

CMAKE_OPTS=("-DCMAKE_EXPORT_COMPILE_COMMANDS=1")

if [ "$1" = "thirdparty" ]; then
	shift 1
	cd pioneer-thirdparty/ && autoconf && ./configure && make assimp && make sdl2 && make sdl2_image && cd ../
	CMAKE_OPTS+=("-DUSE_PIONEER_THIRDPARTY=1")
elif [ "$1" = "cmake" ]; then
	shift 1
fi

CMAKE_OPTS+=("$@")

mkdir -p build; cd build
cmake .. "${CMAKE_OPTS[@]}"
