#!/bin/sh
# Executable wrapper script
# Ensures the program is up-to-date, then hands over

set -e
cd "$(dirname "$0")"
PROGRAM_NAME="$(basename "$0")"

# Create build directory
[ -d build ] || make build
cd build

# Generate build files
[ -f Makefile ] || cmake ..

# Generate binaries
make

# Run main binary
cd ..
exec build/$PROGRAM_NAME "$@"
