-- Copyright © 2008-2023 Pioneer Developers. See AUTHORS.txt for details
-- Licensed under the terms of the GPL v3. See licenses/GPL-3.txt

-- THIS FILE IS AUTO-GENERATED, CHANGES WILL BE OVERWRITTEN
-- enum table generated by scan_enums.py

---@meta

-- ============================================================================

-- Document lua Constants as typed subclasses of string for API visibility sake

-- A <Constants.PhysicsObjectType> string
---@class PhysicsObjectType: string

-- A <Constants.ShipAIError> string
---@class ShipAIError: string

-- A <Constants.ShipFlightState> string
---@class ShipFlightState: string

-- A <Constants.ShipJumpStatus> string
---@class ShipJumpStatus: string

-- A <Constants.ShipAlertStatus> string
---@class ShipAlertStatus: string

-- A <Constants.ShipAICmdName> string
---@class ShipAICmdName: string

-- A <Constants.DualLaserOrientation> string
---@class DualLaserOrientation: string

-- A <Constants.ShipTypeTag> string
---@class ShipTypeTag: string

-- A <Constants.DockingRefusedReason> string
---@class DockingRefusedReason: string

-- A <Constants.ProjectableTypes> string
---@class ProjectableTypes: string

-- A <Constants.ProjectableBases> string
---@class ProjectableBases: string

-- A <Constants.SystemViewMode> string
---@class SystemViewMode: string

-- A <Constants.SystemViewColorIndex> string
---@class SystemViewColorIndex: string

-- A <Constants.PolitEcon> string
---@class PolitEcon: string

-- A <Constants.PolitGovType> string
---@class PolitGovType: string

-- A <Constants.BodyType> string
---@class BodyType: string

-- A <Constants.BodySuperType> string
---@class BodySuperType: string

-- A <Constants.DetailLevel> string
---@class DetailLevel: string

-- A <Constants.FileSystemRoot> string
---@class FileSystemRoot: string

-- A <Constants.PiGuiFaceFlags> string
---@class PiGuiFaceFlags: string

-- A <Constants.ModelDebugFlags> string
---@class ModelDebugFlags: string

-- A <Constants.CruiseDirection> string
---@class CruiseDirection: string

-- A <Constants.FollowMode> string
---@class FollowMode: string

-- A <Constants.ShipTypeThruster> string
---@class ShipTypeThruster: string

-- A <Constants.PropulsionFuelStatus> string
---@class PropulsionFuelStatus: string

-- A <Constants.ShipControllerFlightControlState> string
---@class ShipControllerFlightControlState: string

-- ============================================================================

-- Global Constants namespace
Constants = {}

---@type PhysicsObjectType[]
Constants.PhysicsObjectType = {}

---@type ShipAIError[]
Constants.ShipAIError = {}

---@type ShipFlightState[]
Constants.ShipFlightState = {}

---@type ShipJumpStatus[]
Constants.ShipJumpStatus = {}

---@type ShipAlertStatus[]
Constants.ShipAlertStatus = {}

---@type ShipAICmdName[]
Constants.ShipAICmdName = {}

---@type DualLaserOrientation[]
Constants.DualLaserOrientation = {}

---@type ShipTypeTag[]
Constants.ShipTypeTag = {}

---@type DockingRefusedReason[]
Constants.DockingRefusedReason = {}

---@type ProjectableTypes[]
Constants.ProjectableTypes = {}

---@type ProjectableBases[]
Constants.ProjectableBases = {}

---@type SystemViewMode[]
Constants.SystemViewMode = {}

---@type SystemViewColorIndex[]
Constants.SystemViewColorIndex = {}

---@type PolitEcon[]
Constants.PolitEcon = {}

---@type PolitGovType[]
Constants.PolitGovType = {}

---@type BodyType[]
Constants.BodyType = {}

---@type BodySuperType[]
Constants.BodySuperType = {}

---@type DetailLevel[]
Constants.DetailLevel = {}

---@type FileSystemRoot[]
Constants.FileSystemRoot = {}

---@type PiGuiFaceFlags[]
Constants.PiGuiFaceFlags = {}

---@type ModelDebugFlags[]
Constants.ModelDebugFlags = {}

---@type CruiseDirection[]
Constants.CruiseDirection = {}

---@type FollowMode[]
Constants.FollowMode = {}

---@type ShipTypeThruster[]
Constants.ShipTypeThruster = {}

---@type PropulsionFuelStatus[]
Constants.PropulsionFuelStatus = {}

---@type ShipControllerFlightControlState[]
Constants.ShipControllerFlightControlState = {}

