#
# Winding is always CCW. DEVIATION SHOULD BE CONSIDERED A BUG!!11
#
# To get an idea of scale, a double-decker bus is 11m long and a
# boeing 747 is 71m long

model(building1, scale=1.0, radius=10.0) {
	material(.5, .5, .5, 0,0,0, 2.0, 0, 0, 0)
	extrusion(v(0,0,-7.5), v(0,0,7.5), n(0,1,0), radius=6.0, {
		v(-1,0,0), v(1,0,0), v(1,1,0), v(-1,1,0)
	})
}

model(building2, scale=1.0, radius=20.0) {
	material(.5, .5, .5, 0,0,0, 2.0, 0, 0, 0)
	extrusion(v(0,0,-16), v(0,0,16), n(0,1,0), radius=1.0, {
		v(-16,0,0), v(16,0,0), v(16,20,0), v(-16,20,0)
	})
}

# 64x64m is rough dimensions of WTC base
model(building3, scale=1.0, radius=40.0) {
	material(.5, .5, .5, 0,0,0, 2.0, 0, 0, 0)
	extrusion(v(0,0,-32), v(0,0,32), n(0,1,0), radius=1.0, {
		v(-32,0,0), v(32,0,0), v(32,10,0), v(-32,10,0)
	})
}

model(factory1, scale=1.0, radius=30.0) {
	lod { full, 10px, 2px }
	objlod a = { 16, 8, 4 }
	material(.5, .5, .3, 0,0,0, 2.0, 0, 0, 0)
	extrusion(v(0,0,-20), v(0,0,20), n(0,1,0), radius=1.0, {
		v(-20,0,0), v(20,0,0), v(20,20,0), v(-20,20,0)
	})
	extrusion(v(0,0,-20), v(0,0,20), n(0,1,0), radius=1.0, {
		v(-20,20,0), v(0,20,0), v(0,28,0), v(-2,30,0), v(-18,30,0),
		v(-20,28,0)
	})
	material(.6, .6, .6, 0,0,0, 2.0, 0, 0, 0)
	cylinder(a, v(-10,30,10), v(-10,50,10), v(0,0,1), radius=2.0)
	cylinder(a, v(-10,30,0), v(-10,50,0), v(0,0,1), radius=2.0)
	cylinder(a, v(-10,30,-10), v(-10,50,-10), v(0,0,1), radius=2.0)

}

model(clockhand, scale=1.0, radius=1.0) {
	material(0,0,1, .7,.7,1, 10, 0,0,0)
	tri(v(-0.06, -0.06, 0), v(0.06, -0.06, 0), v(0, 1, 0))
}

model(clock, scale=1.0, radius=1.0) {
	lod { full, 15px }
	material(1,1,1, 0,0,0, 0, 0,0,0)
	circle(12, v(0,0,0), v(0,0,1), v(0,1,0), radius=1.0)
	zbias(v(0,0,0), v(0,0,1))

	material(.5,.5,0, 1,1,0, 10, 0,0,0)
	lod1:text(global:21, v(0,0.85,0), v(0,0,1), v(1,0,0), scale=0.15)
	lod1:text(global:10, v(0.425,0.74,0), v(0,0,1), v(1,0,0), scale=0.15)
	lod1:text(global:11, v(0.74,0.43,0), v(0,0,1), v(1,0,0), scale=0.15)
	lod1:text(global:12, v(0.85,0,0), v(0,0,1), v(1,0,0), scale=0.15)
	lod1:text(global:13, v(0.74,-.425,0), v(0,0,1), v(1,0,0), scale=0.15)
	lod1:text(global:14, v(0.425,-.74,0), v(0,0,1), v(1,0,0), scale=0.15)
	lod1:text(global:15, v(0,-.85,0), v(0,0,1), v(1,0,0), scale=0.15)
	lod1:text(global:16, v(-.425,-.736,0), v(0,0,1), v(1,0,0), scale=0.15)
	lod1:text(global:17, v(-.74,-.425,0), v(0,0,1), v(1,0,0), scale=0.15)
	lod1:text(global:18, v(-.85,0,0), v(0,0,1), v(1,0,0), scale=0.15)
	lod1:text(global:19, v(-.74,.425,0), v(0,0,1), v(1,0,0), scale=0.15)
	lod1:text(global:20, v(-.425,.736,0), v(0,0,1), v(1,0,0), scale=0.15)
	
	minhand = vrotate(v(0,0,1), v(1,0,0), animfn=hour)
	hourhand = vrotate(v(0,0,1), v(1,0,0), animfn=halfday)

	subobject(clockhand, v(0,0,0.001), minhand, v(0,0,1), scale=0.65)
	subobject(clockhand, v(0,0,0.001), hourhand, v(0,0,1), scale=0.5)
}

model(church, scale=1.0, radius=22.0) {
	lod { full, 10px }
	material(.5, .5, .3, 0,0,0, 2.0, 0, 0, 0)
	extrusion(v(0,0,-18), v(0,0,12), n(0,1,0), radius=1.0, {
		v(-7,0,0), v(7,0,0), v(7,10,0), v(-7,10,0)
	})
	extrusion(v(0,0,-18), v(0,0,-4), n(0,1,0), radius=1.0, {
		v(-7,10,0), v(7,10,0), v(7,25,0), v(-7,25,0)
	})
	roof1 = v(0,20,12)
	roof2 = v(0,20,-4)
	spire = v(0,45,-11)
	tri(v(-7,10,12), v(7,10,12), roof1)
	material(.8, .3, .0, 0,0,0, 2.0, 0, 0, 0)
	xref:quad(roof2, roof1, v(7,10,12), v(7,10,-4))
	xref:tri(spire, v(7,25,-4), v(7,25,-18))
	tri(spire, v(-7,25,-4), v(7,25,-4))
	tri(spire, v(7,25,-18), v(-7,25,-18))

	clockpos1 = v(-7,18,-11)
	clockpos2 = v(7,18,-11)
	
	lod1:zbias(clockpos1, v(-1,0,0))
	lod1:subobject(clock, clockpos1, v(0,1,0), v(-1,0,0), scale=2.5)
	lod1:zbias(clockpos2, v(1,0,0))
	lod1:subobject(clock, clockpos2, v(0,1,0), v(1,0,0), scale=2.5)
#subobject(object_name, vector pos, vector up, vector zaxis [, scale=float, animfn=])
}

model(nosewheel, scale=1.0, radius=7.0) {
	lod { full, 4px }
	objlod a = { 8, 4 }
	v6 = v(0, 0, 0)
	v7 = v(0, 3, 0)
	v8 = v(0, 5, 0)
	material(.5, .5, .5, .5, .5, .5, 2.0, 0, 0, 0)
	cylinder(a, v6, v8, v(0,0,1), radius=.4)
	cylinder(a, v7, v8, v(0,0,1), radius=.5)
	material(.3, .3, .3, 0,0,0, 1, 0, 0, 0)
	xref:cylinder(a, v(.5,5,0), v(1,5,0), v(0,0,1), radius=1.0)
}

model(nosewheelunit, scale=1.0, radius=7.0) {
	lod { full }
	v6 = v(1.5, 0, 6) # flaps
	v7 = v(1.5, 0, -1)
	v8 = v(0, 0, 6)
	v9 = v(0, 0, -1)
	v10 = v(1.5, 1.5, 6)
	v11 = v(1.5, 1.5, -1)
	tan1 = v(0, 1.5, 0) # tangents
	tan2 = v(-1.5, 0, 0)

	v20 = vhermite(v8, v10, tan1, tan2, animfn=gflap)
	v21 = vhermite(v9, v11, tan1, tan2, animfn=gflap)
	v22 = vlinear(v(0,0,1), v(0,1,0), animfn=gear)
	v23 = vcross(v(1,0,0), v22)

	material(.2,.2,.2, 0,0,0, 1, 0,0,0)
	xref:quad(v8, v6, v7, v9) # flap internal
	material(2)
	xref:quad(v6, v20, v21, v7)
	xref:quad(v6, v7, v21, v20)

	subobject(nosewheel, v(0,0,0), v22, v23, scale=1.0)
}

model(mainwheel, scale=1, radius=8) {
	lod { full, 50px, 10px }
	objlod a = { 16, 8, 4 }
	v6 = v(0,0,0)
	v7 = v(0,3,0)
	v8 = v(0,5,0)
	v13 = v(0, 5, 1.4) # crossbar
	v14 = v(0, 5, -1.4)

	material(.5,.5,.5, 1,1,1, 2, 0,0,0)
	cylinder(a, v6, v8, v(0,0,1), radius=.4)
	cylinder(a, v7, v8, v(0,0,1), radius=.5)
	cylinder(4, v13, v14, v(1,0,0), radius=.5)
	material(.3,.3,.3, 0,0,0, 1, 0,0,0)
	xref:cylinder(a, v(.5, 5, 1.1), v(1, 5, 1.1), v(0,0,1), radius=1)
	xref:cylinder(a, v(.5, 5, -1.1), v(1, 5, -1.1), v(0,0,1), radius=1)
}


model(mainwheelunit, scale=1.0, radius=8.0) {
	lod { full }
	v6 = v(1.5, 0, 6) # flap
	v7 = v(1.5, 0, -1)
	v8 = v(0, 0, 6)
	v9 = v(0, 0, -1)
	v10 = v(1.5, 1.5, 6)
	v11 = v(1.5, 1.5, -1)
	tan1 = v(0, 1.5, 0)
	tan2 = v(-1.5, 0, 0)
	v20 = vhermite(v8, v10, tan1, tan2, animfn=gflap)
	v21 = vhermite(v9, v11, tan1, tan2, animfn=gflap)
	v22 = vlinear(v(0,0,1), v(0,1,0), animfn=gear)
	v23 = vcross(v(1,0,0), v22)

	material(.2,.2,.2, 0,0,0, 1, 0,0,0)
	xref:quad(v8, v6, v7, v9) # flap internal
	material(2)
	xref:quad(v6, v20, v21, v7)
	xref:quad(v6, v7, v21, v20)
	subobject(mainwheel, v(0,0,0), v22, v23, scale=1.0)
}

# Ship 
model(taipan, scale=1.0, radius=60.0) {
	lod { full, 40px, 20px, 5px }
	objlod slod_a = { 8, 4, 2, 1 }
	objlod slod_tube = { 16, 10, 8, 4 }
	
	# right bot/top of +z extrusion end
	box_bot = v(15,-5,50)
	box_top = v(15,5,50)
	box_bot_flange = v(16,-5,51)
	box_top_flange = v(16,5,51)
	wingtip = v(40,-3,40)
	front_wingtip = v(15,-5,-30)
	material(.3,.3,.3, .6,.6,.6, 100, 0,0,0)
	# rear
	quad(box_top, v(-15,5,50), v(-15,-5,50), box_bot)
	# arse flange
	xref:quad(
		box_bot,
		box_bot_flange,
		box_top_flange,
		box_top
	)
	# arse curved bits
	xref:smooth(slod_a, 
		line(wingtip),
		hermite(box_top_flange, v(-50,0,20), v(50,-30,-20)), # herm 1
		line(box_bot_flange))
	# top of wing
	xref:smooth(slod_a, 
		hermite(wingtip, v(50,-30,-20), v(-50,0,20)), # herm 1
		hermite(front_wingtip, v(0,0,-80), v(40,0,40)), # herm 2 leading edge
#			line(v(15, 5, -30)),
		line(box_top),
		line(box_top_flange))
	# bottom of wing
	xref:flat(slod_a, v(0,-1,0),
		line(box_bot),
		line(front_wingtip),
		hermite(wingtip, v(40,0,40), v(0,0,-80)), # herm3 leading edge lower
		line(box_bot_flange))
	# inner wing bit
	xref:tri(front_wingtip, box_bot, box_top)

	# top and bottom at rear
	quad(box_top, v(15,4.3,45), v(-15,4.3,45), v(-15,5,50))
	quad(box_bot, v(-15,-5,50), v(-15,-5,35), v(15,-5,35))
	quad(v(15,-5,35), v(-15,-5,35), v(-15,1,30), v(15,1,30))

	tri(v(-15,4.3,45), v(15,4.3,45), v(0, 3.5, 35))
#		xref:quad(v(0,4,35), v(15,5,45), v(15,4,35), v(0,3.5,25))

	# make materials be assignable
	material(.3,0,0, .7,0,0, 100, 0,0,0)
	xref:tri(v(0,3.5,35),v(15,4.3,45), v(15,3,35))
	material(.3,.3,.3, .6,.6,.6, 100, 0,0,0)
	# top body bit
	tanTipR = v(20,10,50)
	tanTipL = v(-20,10,50)
	tanFwd = v(0,-10,-50)
	smooth(slod_a, 
		line(v(15,3,35)),
		hermite(v(0,-2,0), tanFwd, tanTipR),
		hermite(v(-15,3,35), tanTipL, tanFwd),
		line(v(0,3.5,35)))
	
	smooth(slod_a,
		hermite(v(0,-2,0), tanFwd, tanTipL),
		hermite(v(15,3,35), tanTipR, tanFwd),
		hermite(v(-15,3,35), v(0,-30,0), v(0,-30,0)))

	xref:smooth(slod_a, 
		hermite(v(15,-5,-10), v(-10,0,0), v(-10,0,0)),
		line(v(15,-5,50)),
		hermite(v(15,5,50), v(-10,0,0), v(-10,0,0)),
		line(v(15,-2.5,-10)))

	# engines
	material(.1,.1,.1, .7,.7,.7, 150.0, 0,0,0)
	
	# front
	# rear
	tube(slod_tube, v(0,0,50), v(0,0,52), v(0,1,0), innerrad=3.5, outerrad=4)
	xref:tube(slod_tube, v(10,0,50), v(10,0,52), v(0,1,0), innerrad=3.5, outerrad=4)
	material(animfn=thrustpulse,
		material(0,0,0, 0,0,0, 0, .2,.2,1),
		material(0,0,0, 0,0,0, 0, .7,.7,1))
	# front
	xref:flat(slod_a, v(0,0,-1),
		line(v(15,-5,-10)),
		hermite(v(15,-2.5,-10), v(-10,0,0), v(-10,0,0)))
	#rear
	zbias(v(0,0,50), v(0,0,1))
	circle(slod_tube, v(0,0,50), v(0,0,1), v(0,1,0), radius=3.5)
	xref:circle(slod_tube, v(10,0,50), v(0,0,1), v(0,1,0), radius=3.5)
#	xref:circle(slod_tube, v(10,0,3), v(0,0,-1), v(0,1,0), radius=2.5)
	nozbias()

	# license plate
	material(.9,.9,.9, 0,0,0, 0, 0,0,0)
	idtext_pos = v(0, 4.65, 47.5)
	zbias(idtext_pos, v(0,0,1))
	lod1:text(params:0, idtext_pos,
		vnormal(
		v(-15,4.3,45),
		v(-15,5,50),
		box_top
		),
		v(1,0,0), scale=3)
	
	xref:notangular:thruster(fwd, v(10,0,50), 50.0)
	notangular:thruster(fwd, v(0,0,50), 50.0)
	xref:notangular:thruster(rev, v(14,-3.75,-10), 25.0)
	
	xref:thruster(down, v(18, 5, 45), 10.0)
	xref:thruster(down, v(18, -4, -20), 10.0)
	xref:thruster(up, v(18, -5, 45), 10.0)
	xref:thruster(up, v(18, -5, -20), 10.0)

	thruster(left, v(18, 0, 50), 15.0)
	thruster(right, v(-18, 0, 50), 15.0)
	
	subobject(nosewheelunit, v(22,-5,0), v(0,-1,0), v(0,0,1), scale=1.0, animfn=gear)
	subobject(nosewheelunit, v(-22,-5,0), v(0,-1,0), v(0,0,1), scale=1.0, animfn=gear)
	subobject(mainwheelunit, v(12,-5,40), v(0,-1,0), v(0,0,1), scale=1.0, animfn=gear)
	subobject(mainwheelunit, v(-12,-5,40), v(0,-1,0), v(0,0,1), scale=1.0, animfn=gear)
}

model(hermite_wank, scale=1, radius=1) {
	# 1/8th sphere
	v6 = v(0.0, 5.0, 0.0)
	v7 = v(-5.0, 0.0, 0.0 )
	v8 = v(0.0, 0.0, 5.0 )

	v9 = v(-7.0, 0.0, 0.0 )			
	v10 = v(0.0, 7.0, 0.0 )
	v11 = v(0.0, 0.0, 7.0 )			
	material(.2,.0,.2, 1,0,1, 10, 0,0,0)
	xref:smooth(8, 
		hermite(v7, v9, v10),
		hermite(v8, v11, v9),
		hermite(v6, v10, v11))

	material(1, 0, 1, 0, 0, 0, 1, 0, 0, 0)
	extrusion(v(0,0,0), v(0,0,10), n(0,-1,0), radius=1.0,
		{
			v(-3.0, 0.0, 0),
			v(-2.0, -2.0, 0),
			v(2.0, -2.0, 0),			
			v(6.0, 0.0, 0),			
			v(2.0, 2.0, 0),
			v(-2.0, 2.0, 0)
		})
	xref:notangular:thruster(fwd, v(10,0,0), 30.0)
	xref:thruster(rev, v(10,0,0), 10.0)
	xref:thruster(up, v(10,0,0), 20.0)
	xref:thruster(down, v(10,0,0), 20.0)
	thruster(left, v(0,0,0), 20.0)
	thruster(right, v(0,0,0), 20.0)
}

model(junk, scale=1.5, radius=1.0) {
	lod { full, 5px, 2.5px }
	objlod arse = { 16, 10, 8 }
	
	material(.5,.5,.5,0,0,0, 0, 0,0,0)
	geomflag(10)
	xref:tube(arse, v(15,-20,0), vlinear(v(15,-15,0), v(15,-10,0), animfn=gear), v(0,0,1), innerrad=5.0, outerrad=10.0)
	quad(v(1,-2,0), v(1,-1,0), v(0,-1,0), v(0,-2,0))
	circle(arse, v(15,0,0), v(0,0,1), v(0,1,0), radius=10.0)
	xref:cylinder(arse, v(15,10,0), v(15,20,0), v(0,0,1), radius=10.0)

	subobject(hermite_wank, v(0,0,0), v(0,1,0), v(0,0,1), scale=1.0)
	subobject(hermite_wank, v(0,0,0), v(0,-1,0), v(0,0,1), scale=1.0, animfn=gear)
}

model(cargo, scale=1.0, radius=1.0) {
	lod { full, 10px, 5px }
	objlod cyl_lod = { 16, 16, 8 }

	top = v(0,1,0)
	bottom = v(0,-1,0)
	textpos = v(0,0.8,0)

	material(.5,.5,.5, 0,0,0, 0, 0,0,0)
	lod2:lod3:cylinder(cyl_lod, top, bottom, v(1,0,0), radius=1.0)
	
	lod1:tube(16, top, bottom, v(1,0,0), innerrad=0.9, outerrad=1.0)
	lod1:cylinder(16, textpos, v(0,-0.8,0), v(1,0,0), radius=0.9)
	lod1:material(1,0,0, 0,0,0, 0, 0,0,0)
	lod1:zbias(textpos, v(0,1,0))
	lod1:text(params:0, textpos, v(0,1,0), v(1,0,0), scale=0.1)
}

