#ifndef _EQUIPTYPE_H
#define _EQUIPTYPE_H

namespace Equip {
	enum Slot { SLOT_CARGO, SLOT_ENGINE, SLOT_LASER, SLOT_MISSILE, SLOT_ECM, SLOT_SCANNER, SLOT_RADARMAPPER, SLOT_HYPERCLOUD, SLOT_HULLAUTOREPAIR, SLOT_ENERGYBOOSTER, SLOT_MAX };
	enum Type { NONE, HYDROGEN, LIQUID_OXYGEN, METAL_ORE, CARBON_ORE, METAL_ALLOYS, PLASTICS, FRUIT_AND_VEG, ANIMAL_MEAT, LIQUOR, GRAIN, TEXTILES, FERTILIZER, WATER, MEDICINES, CONSUMER_GOODS, COMPUTERS, ROBOTS, PRECIOUS_METALS, INDUSTRIAL_MACHINERY, FARM_MACHINERY, MINING_MACHINERY, AIR_PROCESSORS, HAND_WEAPONS, BATTLE_WEAPONS, NERVE_GAS, NARCOTICS,
	
	MISSILE_UNGUIDED, MISSILE_GUIDED, MISSILE_SMART, MISSILE_NAVAL, ECM_BASIC, SCANNER, ECM_ADVANCED, SHIELD_GENERATOR,
	RADAR_MAPPER, HYPERCLOUD_ANALYZER, HULL_AUTOREPAIR, SHIELD_ENERGY_BOOSTER,
	DRIVE_INTERPLANETARY, DRIVE_CLASS1, DRIVE_CLASS2, DRIVE_CLASS3, DRIVE_CLASS4, DRIVE_CLASS5, DRIVE_CLASS6, DRIVE_CLASS7,
	PULSECANNON_1MW, PULSECANNON_DUAL_1MW, PULSECANNON_2MW, PULSECANNON_4MW, PULSECANNON_10MW, PULSECANNON_20MW, TYPE_MAX,
	FIRST_COMMODITY=HYDROGEN, LAST_COMMODITY=NARCOTICS,
        FIRST_SHIPEQUIP=MISSILE_UNGUIDED, LAST_SHIPEQUIP=PULSECANNON_20MW
	};
};

#define EQUIP_INPUTS	2

struct EquipType {
	const char *name;
	const char *description;
	Equip::Slot slot;
	Equip::Type inputs[EQUIP_INPUTS]; // production requirement. eg metal alloys input would be metal ore
	int basePrice;
	int mass;
	int pval; // hello angband. used for general 'power' attribute...
	int econType;
	int techLevel; /* 0-5 */
	float rechargeTime;
	
	static const EquipType types[];
};

#endif /* _EQUIPTYPE_H */
